### PR TITLE
fix: Filter out inactive meetings in upcoming meetings widget

### LINKED ISSUE #398: Upcoming Active Meetings
This could be a feature or a bug. Putting it here.

When people go to the website to find a meeting, they want to see upcoming meetings (and only active ones). This issue is different from #396.  

@joshreisner setup the UI version to show all the meetings for the week, starting from the time zone the user views it. That would be ideal since we'd no longer run into no meetings to display if it's late in the evening.

I don't know if you work on the WordPress TSML Widgets, but the Upcoming Meeting Widget would be great if there was a way to filter out inactive meetings and work in a similar fashion. It does give you the capability to select how many meetings you want to have displayed.

Thanks.

### PR DESCRIPTION
**Pull request by tech2serve**
Logically, inactive meetings shouldn't be shown in the widget that
is specifically designed to show the user the near term meetings available
for them to attend.

closes #398
answers #422

### CODE REVIEW

File: includes/filter_meetings.php [hunk 1]
```diff
@@ -93,6 +93,7 @@ public function __construct($arguments)
                 $this->attendance_option[] = 'hybrid';
             }
             if (!empty(array_intersect($this->attendance_option, Array('active')))) {
+                $this->attendance_option = [];
```
Comment (joshreisner) [inline includes/filter_meetings.php:96]: @tech2serve `[]` will fail on some versions of PHP. better to use `array()`

Comment (tech2serve) [reply includes/filter_meetings.php]: Fixed. Thanks.

**Comment by joshreisner** [comment]
this seems good! and seems to do what you want. not worth holding it up, but a cleaner way of expressing

```
if (!empty(array_intersect($this->attendance_option, Array('active')))) {
    $this->attendance_option = array();
    $this->attendance_option[] = 'hybrid';
    $this->attendance_option[] = 'in_person';
    $this->attendance_option[] = 'online';
}
```

is

```
if (in_array('active', $this->attendance_option)) {
    $this->attendance_option = array('hybrid', 'in_person', 'online');
}
```

**Comment by joshreisner** [comment]
instead of 

```
$meetings = tsml_get_meetings(array('day' => intval(current_time('w')), 'time' => 'upcoming'));
$filter_arguments['attendance_option'] = 'active';
$filter = new tsml_filter_meetings($filter_arguments);
$meetings = $filter->apply($meetings);
```

i think it might be better to do

```
$meetings = tsml_get_meetings(array('day' => intval(current_time('w')), 'time' => 'upcoming'));
$filter_arguments['attendance_option'] = 'active';
$filter = new tsml_filter_meetings($filter_arguments);
$meetings = $filter->apply($meetings);
```

it would be more efficient to do

```
$meetings = tsml_get_meetings(array(
	'day' => intval(current_time('w')), 
	'time' => 'upcoming',
	'attendance_option' => 'active',
));
```
because otherwise you're running `tsml_filter_meetings` twice (because `tsml_get_meetings` already does that). i confirmed this works in my local

**Comment by joshreisner** [comment]
(hope you don't mind i just pushed those two changes to the branch)

**Comment by tech2serve** [comment]
> this seems good! and seems to do what you want. not worth holding it up, but a cleaner way of expressing
> 
> ```
> if (!empty(array_intersect($this->attendance_option, Array('active')))) {
>     $this->attendance_option = array();
>     $this->attendance_option[] = 'hybrid';
>     $this->attendance_option[] = 'in_person';
>     $this->attendance_option[] = 'online';
> }
> ```
> 
> is
> 
> ```
> if (in_array('active', $this->attendance_option)) {
>     $this->attendance_option = array('hybrid', 'in_person', 'online');
> }
> ```

Works for me.

@brianw-area24?
