### PR TITLE
Fixing undefined index error on upcoming meetings shortcode

### LINKED ISSUE #1094: Notice shown from upcoming meetings widget when in person meeting has no types
### Discussed in https://github.com/code4recovery/12-step-meeting-list/discussions/1093

<div type='discussions-op-text'>

<sup>Originally posted by **district6wc** March 16, 2023</sup>
I was working on my site tonight and when I updated my homepage this appeared on my sidebar:

Notice: Undefined index: types in /home/izgr1zclaxch/public_html/wp-content/plugins/12-step-meeting-list/includes/shortcodes.php on line 30
Notice: Undefined index: types in /home/izgr1zclaxch/public_html/wp-content/plugins/12-step-meeting-list/includes/shortcodes.php on line 36

This is my site https://alanonalateen6nc.org/

How do I correct this?

Rose L
District 6</div>

### PR DESCRIPTION
**Pull request by anchovie91471**
When in-person meeting has no types, php throws Notice: Undefined index: types

Added array_key_exists check inside tsml_next_meetings() function.

closes #1094

### CODE REVIEW

File: includes/shortcodes.php [hunk 1]
```diff
@@ -27,13 +27,14 @@ function tsml_next_meetings($arguments)
 	$meetings = array_slice($meetings, 0, $arguments['count']);
 	$rows = '';
 	foreach ($meetings as $meeting) {
-		$classes = tsml_to_css_classes($meeting['types']);
+		if (array_key_exists('types', $meeting))
+			$classes = tsml_to_css_classes($meeting['types']);
```
Comment (joshreisner) [inline includes/shortcodes.php:31]: looks good! two small suggestions:

when dealing with undefined key notices, we typically use `if (!empty(` as below because it won't throw a notice and will also tell us if there's a value there.

also i wonder if this could be combined with the two other if statements here like this:

```
$meeting_types = '';
if (!empty($meeting['types'])) {
  $classes = tsml_to_css_classes($meeting['types']);
  $meeting_types = tsml_format_types($meeting['types']);
}
```

then we could get rid of lines 37-40

Comment (anchovie91471) [reply includes/shortcodes.php]: OK, Just committed that.

**Review by joshreisner — APPROVED** [review]
works great, thanks! changes are approved, so feel free to merge whenever
